package com.example.citationeapp.di

import com.example.citationeapp.data.models.Citation

val citations = mutableListOf(
    Citation(
        0,
        "Are You Not Entertained ?",
        "Est-ce que vous n'êtes pas divertis ?",
        null,
        null,
        "Maximus",
        "Russell Crowe",
        2,
        "movie",
        0,
        emptyList(),
        null
    ),
    Citation(
        1,
        "Death smiles at us all, all we can do is smile back.",
        "La mort nous sourit tous, tout ce que nous pouvons faire, c'est lui sourire en retour.",
        null,
        null,
        "Maximus",
        "Russell Crowe",
        1,
        "movie",
        0,
        emptyList(),
        null
    ),
    Citation(
        2,
        "I will make him an offer he can't refuse.",
        "Je vais lui faire une offre qu'il ne pourra pas refuser.",
        null,
        null,
        "Vito Corleone",
        "Marlon Brando",
        1,
        "movie",
        1,
        emptyList(),
        null
    ),
    Citation(
        3,
        "Me? I'm dishonest, and a dishonest man you can always trust to be dishonest. Honestly. It's the honest ones you want to watch out for, because you can never predict when they're going to do something incredibly... stupid.",
        "Moi ? Je suis malhonnête, et on sait qu'un homme malhonnête le restera quoiqu'il arrive. Honnêtement. Ce sont les hommes honnêtes dont il faut se méfier, car on peut jamais prévoir à quel moment ils font quelque chose d'incroyablement... stupide.",
        null,
        null,
        "Jack Sparrow",
        "Johnny Depp",
        3,
        "movie",
        2,
        emptyList(),
        null
    ),
    Citation(
        4,
        "Say hello to my little friend!",
        "Dis bonjour à mon petit ami !",
        null,
        null,
        "Tony Montana",
        "Al Pacino",
        2,
        "movie",
        3,
        emptyList(),
        null
    ),
    Citation(
        5,
        "Hasta la vista, baby.",
        "Hasta la vista, baby.",
        null,
        null,
        "T-800",
        "Arnold Schwarzenegger",
        1,
        "movie",
        4,
        emptyList(),
        null
    ),
    Citation(
        6,
        "Life is like a box of chocolates. You never know what you're gonna get.",
        "La vie, c'est comme une boîte de chocolats. On ne sait jamais sur quoi on va tomber.",
        null,
        null,
        "Forrest Gump",
        "Tom Hanks",
        1,
        "movie",
        5,
        emptyList(),
        null
    ),
    Citation(
        7,
        "I am your father.",
        "Je suis ton père.",
        null,
        null,
        "Darth Vader",
        "James Earl Jones",
        1,
        "movie",
        6,
        emptyList(),
        null
    ),
    Citation(
        8,
        "Do or do not, there is no try.",
        "Fais-le ou ne le fais pas, mais il n'y a pas d'essai.",
        null,
        null,
        "Yoda",
        "Frank Oz",
        2,
        "movie",
        6,
        emptyList(),
        null
    ),
    Citation(
        9,
        "I see dead people.",
        "Je vois des gens qui sont morts.",
        null,
        null,
        "Cole Sear",
        "Haley Joel Osment",
        2,
        "movie",
        7,
        emptyList(),
        null
    ),
    Citation(
        10,
        "That Belongs in a Museum.",
        "Ça appartient à un musée.",
        null,
        null,
        "Indiana Jones",
        "Harrison Ford",
        2,
        "movie",
        8,
        emptyList(),
        null
    ),
    Citation(
        11,
        "Keep your friends close, but your enemies closer.",
        "Garde tes amis près de toi, mais encore plus près tes ennemis.",
        null,
        null,
        "Michael Corleone",
        "Al Pacino",
        3,
        "movie",
        9,
        emptyList(),
        null
    ),
    Citation(
        12,
        "I spared no expense!",
        "Je n'ai pas regardé à la dépense !",
        null,
        null,
        "John Hammond",
        "Richard Attenborough",
        2,
        "movie",
        10,
        emptyList(),
        null
    ),
    Citation(
        13,
        "Certainty of death. Small chance of success. What are we waiting for?",
        "Certitude de mort. Petite chance de succès. Qu'attendons-nous ?",
        null,
        null,
        "Gimli",
        "John Rhys-Davies",
        2,
        "movie",
        11,
        emptyList(),
        null
    ),
    Citation(
        14,
        "Fly, you fools!",
        "Fuyez, pauvres fous !",
        null,
        null,
        "Gandalf",
        "Ian McKellen",
        2,
        "movie",
        12,
        emptyList(),
        null
    ),
    Citation(
        15,
        "I can't carry it for you, but I can carry you!",
        "Je ne peux pas le porter pour toi, mais je peux te porter, toi !",
        null,
        null,
        "Samwise Gamgee",
        "Sean Astin",
        1,
        "movie",
        11,
        emptyList(),
        null
    ),
    Citation(
        16,
        "If we are to be successful, we must show tact, respect, and a good deal of charm. That's why you must let me do the talking!",
        "Si nous voulons réussir, nous devons faire preuve de tact, de respect et d'un certain charme. C'est pourquoi tu dois me laisser parler !",
        null,
        null,
        "Gandalf",
        "Ian McKellen",
        2,
        "movie",
        13,
        emptyList(),
        null
    ),
    Citation(
        17,
        "Est-ce que j'me suis bien fait compris ?",
        "Est-ce que j'me suis bien fait compris ?",
        null,
        null,
        "Commissaire Gibert",
        "Bernard Farcy",
        1,
        "movie",
        14,
        emptyList(),
        null
    ),
    Citation(
        18,
        "Voilà, cadeau ... de Noël !",
        "Voilà, cadeau ... de Noël !",
        null,
        null,
        "OSS 117",
        "Jean Dujardin",
        2,
        "movie",
        15,
        emptyList(),
        null
    ),
    Citation(
        19,
        "Il y a forcément une amicale d'anciens nazis ? Ou un club ? Une association ?",
        "Il y a forcément une amicale d'anciens nazis ? Ou un club ? Une association ?",
        null,
        null,
        "OSS 117",
        "Jean Dujardin",
        1,
        "movie",
        15,
        emptyList(),
        null
    ),
    Citation(
        20,
        "J'aime me beurrer la biscotte !",
        "J'aime me beurrer la biscotte !",
        null,
        null,
        "OSS 117",
        "Jean Dujardin",
        1,
        "movie",
        16,
        emptyList(),
        null
    ),
    Citation(
        21,
        "Tu n'es pas seulement un lâche, tu es un traître comme ta petite taille le laisser deviner.",
        "Tu n'es pas seulement un lâche, tu es un traître comme ta petite taille le laisser deviner.",
        null,
        null,
        "OSS 117",
        "Jean Dujardin",
        2,
        "movie",
        16,
        emptyList(),
        null
    ),
    Citation(
        22,
        "C'est quoi ce pays ? C'est pas possible. Il fait au moins moins 8000 !",
        "C'est quoi ce pays ? C'est pas possible. Il fait au moins moins 8000 !",
        null,
        null,
        "Numérobis",
        "Jamel Debbouze",
        1,
        "movie",
        17,
        emptyList(),
        null
    ),
    Citation(
        23,
        "Je vais rester ici pour raviver le feu, parce que parfois il s'éteint.",
        "Je vais rester ici pour raviver le feu, parce que parfois il s'éteint.",
        null,
        null,
        "Numérobis",
        "Jamel Debbouze",
        2,
        "movie",
        17,
        emptyList(),
        null
    ),
    Citation(
        24,
        "It takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends.",
        "Il faut beaucoup de courage pour affronter nos ennemis, mais il en faut tout autant pour affronter ses amis.",
        null,
        null,
        "Albus Dumbledore",
        "Richard Harris",
        2,
        "movie",
        18,
        emptyList(),
        null
    ),
    Citation(
        25,
        "I solemnly swear that I am up to no good.",
        "Je jure solennellement que mes intentions sont mauvaises.",
        null,
        null,
        "Fred & George Weasley",
        "James & Oliver Phelps",
        1,
        "movie",
        19,
        emptyList(),
        null
    ),
    Citation(
        26,
        "The thing that frightens you most is fear itself, which is a wise thing.",
        "La chose qui t'effraie le plus, c'est la peur elle-même, ce qui est une chose sage.",
        null,
        null,
        "Remus Lupin",
        "David Thewlis",
        2,
        "movie",
        19,
        emptyList(),
        null
    ),
    Citation(
        27,
        "When we dream, we enter a world that is entirely our own.",
        "Quand nous rêvons, nous entrons dans un monde qui est entièrement le nôtre.",
        null,
        null,
        "Albus Dumbledore",
        "Michael Gambon",
        2,
        "movie",
        19,
        emptyList(),
        null
    ),
    Citation(
        28,
        "Soon, we must all face the choice between what is right and what is easy.",
        "Bientôt, nous devrons tous affronter le choix entre ce qui est juste et ce qui est facile.",
        null,
        null,
        "Albus Dumbledore",
        "Michael Gambon",
        2,
        "movie",
        20,
        emptyList(),
        null
    ),
    Citation(
        29,
        "Mankind was born on Earth. It was never meant to die here.",
        "L'humanité est née sur Terre. Elle n'était pas censée y mourir.",
        null,
        null,
        "Cooper",
        "Matthew McConaughey",
        2,
        "movie",
        21,
        emptyList(),
        null
    ),
    Citation(
        30,
        "Get busy living, or get busy dying.",
        "Occupe-toi de vivre ou occupe-toi de mourir.",
        null,
        null,
        "Andy Dufresne",
        "Tim Robbins",
        2,
        "movie",
        22,
        emptyList(),
        null
    ),
    Citation(
        31,
        "Any man who must say 'I am the king' is no true king.",
        "Tout homme qui doit dire 'je suis le roi' n'est pas un vrai roi.",
        null,
        null,
        "Tywin Lannister",
        "Charles Dance",
        2,
        "serie",
        23,
        emptyList(),
        null
    ),
    Citation(
        32,
        "A mind needs books as a sword needs a whetstone if it is to keep its edge. That's why I read so much.",
        "Un esprit a besoin de livres comme une épée a besoin d'une pierre à aiguiser pour conserver son tranchant. C'est pour ça que je lis autant.",
        null,
        null,
        "Tyrion Lannister",
        "Peter Dinklage",
        2,
        "serie",
        23,
        emptyList(),
        null
    ),
    Citation(
        33,
        "Lies spread faster than the truth.",
        "Les mensonges se propagent plus vite que la vérité.",
        null,
        null,
        "Tommy Shelby",
        "Cillian Murphy",
        2,
        "movie",
        24,
        emptyList(),
        null
    ),
    Citation(
        34,
        "This is the way.",
        "C'est la voie.",
        null,
        null,
        "The Mandalorian",
        "Pedro Pascal",
        1,
        "serie",
        25,
        emptyList(),
        null
    ),
    Citation(
        35,
        "Monseigneur, c'est de l'or ! De l'or pour vous réveiller !",
        "Monseigneur, c'est de l'or ! De l'or pour vous réveiller !",
        null,
        null,
        "Blaze",
        "Yves Montand",
        2,
        "movie",
        26,
        emptyList(),
        null
    ),
    Citation(
        36,
        "I love you three thousand times more.",
        "Je t'aime trois mille fois plus.",
        null,
        null,
        "Morgan Stark",
        "Lexi Rabe",
        2,
        "movie",
        27,
        emptyList(),
        null
    ),
    Citation(
        37,
        "Tu es comme le H de Hawaï, tu sers à rien.",
        "Tu es comme le H de Hawaï, tu sers à rien.",
        null,
        null,
        "Brice",
        "Jean Dujardin",
        2,
        "movie",
        28,
        emptyList(),
        null
    ),
    Citation(
        38,
        "Sometimes your whole life boils down to one insane move.",
        "Parfois, toute votre vie se résume à un geste insensé.",
        null,
        null,
        "Jake Sully",
        "Sam Worthington",
        2,
        "movie",
        29,
        emptyList(),
        null
    ),
    Citation(
        39,
        "Champions du monde !",
        "Champions du monde !",
        null,
        null,
        "Serge Benamou",
        "José Garcia",
        2,
        "movie",
        30,
        emptyList(),
        null
    ),
    Citation(
        40,
        "Daddy, I want another pony!",
        "Papa, je veux un autre poney !",
        null,
        null,
        "Veruca Salt",
        "Julia Winter",
        2,
        "movie",
        31,
        emptyList(),
        null
    ),
    Citation(
        41,
        "Pas commencer à jouer avec mes couilles, ok ?",
        "Pas commencer à jouer avec mes couilles, ok ?",
        null,
        null,
        "Claudy Focan",
        "François Damiens",
        1,
        "movie",
        32,
        emptyList(),
        null
    ),
    Citation(
        42,
        "Il a une tête de vainqueur.",
        "Il a une tête de vainqueur.",
        null,
        null,
        "Pierre Brochant",
        "Thierry Lhermitte",
        1,
        "movie",
        33,
        emptyList(),
        null
    ),
    Citation(
        43,
        "Ohhh, c'est très tordu, mais terriblement astucieux.",
        "Ohhh, c'est très tordu, mais terriblement astucieux.",
        null,
        null,
        "François Pignon",
        "Jacques Villeret",
        1,
        "movie",
        33,
        emptyList(),
        null
    ),
    Citation(
        44,
        "You see, in this world, there are two kinds of people, my friend: Those with loaded guns, and those who dig. You dig.",
        "Tu vois, dans ce monde, il y a deux catégories de personnes, mon ami : ceux qui ont un pistolet chargé et ceux qui creusent. Toi, tu creuses.",
        null,
        null,
        "Blondie",
        "Clint Eastwood",
        2,
        "movie",
        34,
        emptyList(),
        null
    ),
    Citation(
        45,
        "Si j'avais su, je ne serais pas venu.",
        "Si j'avais su, je ne serais pas venu.",
        null,
        null,
        "Petit Gibus",
        "Martin Lartigue",
        1,
        "movie",
        35,
        emptyList(),
        null
    ),
    Citation(
        46,
        "You talkin' to me? You talkin' to ME? You talkin' to me?",
        "C'est à moi que tu parles ? C'est à moi que tu parles ? C'est à moi que tu parles ?",
        null,
        null,
        "Travis Bickle",
        "Robert De Niro",
        1,
        "movie",
        36,
        emptyList(),
        null
    ),
    Citation(
        47,
        "I will not part with a single piece of gold, not the smallest bit.",
        "Je ne me séparerai d'aucun morceau d'or, pas le plus petit.",
        null,
        null,
        "Thorin Oakenshield",
        "Richard Armitage",
        2,
        "movie",
        37,
        emptyList(),
        null
    ),
    Citation(
        48,
        "Au revoir, Shoshanna!",
        "Au revoir, Shoshanna !",
        null,
        null,
        "Col. Hans Landa",
        "Christoph Waltz",
        1,
        "movie",
        38,
        emptyList(),
        null
    ),
    Citation(
        49,
        "I used to think my life was a tragedy, but now I realize it's a comedy.",
        "Je pensais que ma vie était une tragédie, mais maintenant je me rends compte que c'est une comédie.",
        null,
        null,
        "Arthur Fleck",
        "Joaquin Phoenix",
        2,
        "movie",
        39,
        emptyList(),
        null
    ),
    Citation(
        50,
        "Yesterday is history, tomorrow is a mystery, but today is a gift. That is why it is called the present.",
        "Hier est derrière, demain est mystère, et aujourd'hui est un cadeau, c'est pour cela qu'on l'appelle le présent.",
        null,
        null,
        "Master Oogway",
        "",
        2,
        "movie",
        40,
        emptyList(),
        null
    ),
    Citation(
        51,
        "J'ai glissé chef !",
        "J'ai glissé chef !",
        null,
        null,
        "Pitivier",
        "",
        2,
        "movie",
        41,
        emptyList(),
        null
    ),
    Citation(
        52,
        "I expected nothing, and I’m still let down.",
        "Je m'attendais à rien et je suis quand même déçu.",
        null,
        null,
        "Dewey",
        "",
        2,
        "serie",
        42,
        emptyList(),
        null
    ),
    Citation(
        53,
        "You live. You live. You die.",
        "Toi, tu vis. Toi, tu vis. Toi, tu crèves.",
        null,
        null,
        "Dewey",
        "",
        1,
        "serie",
        42,
        emptyList(),
        null
    ),
    Citation(
        54,
        "The difference between you and me is that I make this look good.",
        "La différence entre toi et moi, c'est que moi j'ai la classe.",
        null,
        null,
        "J",
        "Will Smith",
        2,
        "movie",
        43,
        emptyList(),
        null
    ),
    Citation(
        55,
        "Les filles c'est comme les penaltys : si tu gamberches trop t'as aucune chance de planter.",
        "Les filles c'est comme les penaltys : si tu gamberches trop t'as aucune chance de planter.",
        null,
        null,
        "",
        "",
        2,
        "movie",
        44,
        emptyList(),
        null
    ),
    Citation(
        56,
        "Lies are necessary when the truth is too difficult to believe.",
        "Les mensonges sont nécessaires quand la vérité est trop difficile à croire.",
        null,
        null,
        "Pablo Escobar",
        "",
        2,
        "serie",
        45,
        emptyList(),
        null
    ),
    Citation(
        57,
        "History isn’t kind to men who play God.",
        "L'histoire n'est pas très indulgente avec les hommes qui se prennent pour Dieu.",
        null,
        null,
        "James Bond",
        "Daniel Craig",
        1,
        "movie",
        46,
        emptyList(),
        null
    ),
    Citation(
        58,
        "I totally agree with the fat one.",
        "J'suis bien d'accord avec la grosse là.",
        null,
        null,
        "",
        "",
        1,
        "movie",
        47,
        emptyList(),
        null
    ),
    Citation(
        59,
        "Tu es le roi des cons au pays des emmerdeurs.",
        "Tu es le roi des cons au pays des emmerdeurs.",
        null,
        null,
        "Caroline",
        "",
        1,
        "movie",
        47,
        emptyList(),
        null
    ),
    Citation(
        60,
        "They won’t fear it until they understand it. And they won’t understand it until they’ve used it.",
        "Ils ne la craindront pas tant qu'ils ne l'auront pas comprise. Et ils ne la comprendront pas tant qu'ils ne l'auront pas utilisée.",
        null,
        null,
        "Robert Oppenheimer",
        "Cillian Murphy",
        2,
        "movie",
        48,
        emptyList(),
        null
    ),
    Citation(
        61,
        "Now I am become Death, the destroyer of worlds.",
        "Maintenant, je suis devenu la Mort, le destructeur des mondes.",
        null,
        null,
        "Robert Oppenheimer",
        "Cillian Murphy",
        1,
        "movie",
        48,
        emptyList(),
        null
    ),
    Citation(
        62,
        "Vous pouvez pas me taper, j'ai des lunettes.",
        "Vous pouvez pas me taper, j'ai des lunettes.",
        null,
        null,
        "Agnan",
        "",
        2,
        "movie",
        49,
        emptyList(),
        null
    ),
    Citation(
        63,
        "Mais enfin j'suis le parrain de ton fils !",
        "Mais enfin j'suis le parrain de ton fils !",
        null,
        null,
        "",
        "François Cluzet",
        1,
        "movie",
        50,
        emptyList(),
        null
    ),
    Citation(
        64,
        "Death is a day worth living for.",
        "La mort est une journée qui mérite d'être vécue.",
        null,
        null,
        "Hector Barbossa",
        "Geoffrey Rush",
        2,
        "movie",
        51,
        emptyList(),
        null
    ),
    Citation(
        65,
        "Anyone can cook.",
        "Tout le monde peut cuisiner.",
        null,
        null,
        "",
        "",
        1,
        "movie",
        52,
        emptyList(),
        null
    ),
    Citation(
        66,
        "Roads? Where we're going, we don't need roads.",
        "La route ? Là où on va, on n'a pas besoin de route !",
        null,
        null,
        "Doc",
        "",
        2,
        "movie",
        53,
        emptyList(),
        null
    ),
    Citation(
        67,
        "Great Scott!",
        "Non de Zeus !",
        null,
        null,
        "Doc",
        "",
        1,
        "movie",
        53,
        emptyList(),
        null
    ),
    Citation(
        68,
        "Je sais pas comment on fait une tête d'innocent, depuis tout petit j'suis coupable.",
        "Je sais pas comment on fait une tête d'innocent, depuis tout petit j'suis coupable.",
        null,
        null,
        "",
        "",
        1,
        "movie",
        54,
        emptyList(),
        null
    ),
    Citation(
        69,
        "It ain't about how hard you can hit, it’s about how hard you can get hit and keep moving forward.",
        "Ce qui compte c'est pas le nombre de coups que tu peux donner, mais c'est le nombre que tu peux encaisser et continuer à avancer.",
        null,
        null,
        "Rocky Balboa",
        "",
        1,
        "movie",
        55,
        emptyList(),
        null
    ),
    Citation(
        70,
        "I am one with the Force, and the Force is with me.",
        "Je fais corps avec la Force, la Force est avec moi.",
        null,
        null,
        "Chirrut Îmwe",
        "",
        1,
        "movie",
        56,
        emptyList(),
        null
    ),
    Citation(
        71,
        "Is it better to live as a monster or die as a good man?",
        "Mieux vaut-il vivre comme un monstre ou mourir en homme bien ?",
        null,
        null,
        "Teddy Daniels",
        "Leonardo DiCaprio",
        1,
        "movie",
        57,
        emptyList(),
        null
    ),
    Citation(
        72,
        "With great power comes great responsibility.",
        "à grand pouvoir, grandes responsabilités.",
        null,
        null,
        "Spider-Man",
        "",
        1,
        "movie",
        58,
        emptyList(),
        null
    ),
    Citation(
        73,
        "Just because you have the ability to speak does not make you intelligent.",
        "Ce n'est pas parce que tu parles que tu es intelligent.",
        null,
        null,
        "Qui-Gon Jinn",
        "Liam Neeson",
        2,
        "movie",
        59,
        emptyList(),
        null
    ),
    Citation(
        74,
        "I don’t like sand. It’s coarse and rough and irritating and it gets everywhere.",
        "Je n'aime pas le sable, il est grossier, agressif, irritant et s'insinue partout.",
        null,
        null,
        "Anakin Skywalker",
        "Hayden Christensen",
        1,
        "movie",
        60,
        emptyList(),
        null
    ),
    Citation(
        75,
        "L'animal qu'on croyait qu'il n'existait pas mais en fait qu'il n'existe !",
        "L'animal qu'on croyait qu'il n'existait pas mais en fait qu'il n'existe !",
        null,
        null,
        "Pablito",
        "Jamel Debbouze",
        1,
        "movie",
        61,
        emptyList(),
        null
    ),
    Citation(
        76,
        "Red alert!",
        "Alerte générale !",
        null,
        null,
        "Commissaire Gibert",
        "",
        1,
        "movie",
        62,
        emptyList(),
        null
    ),
    Citation(
        77,
        "He saved me in every way a person can be saved.",
        "Il m'a sauvée de toutes les façons possibles dont on peut sauver une personne.",
        null,
        null,
        "Rose",
        "",
        2,
        "movie",
        63,
        emptyList(),
        null
    ),
    Citation(
        78,
        "Arrêtez ! Ou je tire une balle dans la tête à la main !",
        "Arrêtez ! Ou je tire une balle dans la tête à la main !",
        null,
        null,
        "Eric",
        "Eric Judor",
        1,
        "movie",
        64,
        emptyList(),
        null
    ),
    Citation(
        79,
        "There’s a snake in my boot!",
        "Il y a un serpent dans ma botte !",
        null,
        null,
        "Woody",
        "",
        2,
        "movie",
        65,
        emptyList(),
        null
    ),
    Citation(
        80,
        "I loved my son from the moment he opened his eyes until the moment you closed them.",
        "J'ai aimé mon garçon du jour ou il a ouvert les yeux jusqu'au moment ou tu les lui as fermés.",
        null,
        null,
        "King Priam",
        "",
        2,
        "movie",
        66,
        emptyList(),
        null
    ),
    Citation(
        81,
        "Tu ferais mieux de faire refaire la façade de ta femme plutôt que celle de ta maison !",
        "Tu ferais mieux de faire refaire la façade de ta femme plutôt que celle de ta maison !",
        null,
        null,
        "Jeff Tuche",
        "Jean-Paul Rouve",
        1,
        "movie",
        67,
        emptyList(),
        null
    ),
    Citation(
        82,
        "Les gens qui bossent, ils exploitent la planète et puis tant pis si ça pète !",
        "Les gens qui bossent, ils exploitent la planète et puis tant pis si ça pète !",
        null,
        null,
        "Jeff Tuche",
        "Jean-Paul Rouve",
        2,
        "movie",
        67,
        emptyList(),
        null
    ),
    Citation(
        83,
        "Tigers love pepper, they hate cinnamon.",
        "Les tigres adorent le poivre, ils détestent la cannelle.",
        null,
        null,
        "Alan",
        "",
        2,
        "movie",
        68,
        emptyList(),
        null
    ),
    Citation(
        84,
        "Messire, messire, un sarrasin dans une charriote du diable ! c'est tout ferré y'a point de beuf pour tirer !",
        "Messire, messire, un sarrasin dans une charriote du diable ! c'est tout ferré y'a point de beuf pour tirer !",
        null,
        null,
        "Jacquouille",
        "Christian Clavier",
        1,
        "movie",
        69,
        emptyList(),
        null
    ),
    Citation(
        85,
        "Time is of no importance, only life is important.",
        "Le temps est sans importance, seule la vie est importante.",
        null,
        null,
        "",
        "",
        2,
        "movie",
        70,
        emptyList(),
        null
    ),
    Citation(
        86,
        "Sometimes it is the people no one imagines anything of who do the things that no one can imagine.",
        "Parfois ce sont les gens que personne n'aurait imaginé qui accomplissent des choses que personne n'avait imaginé.",
        null,
        null,
        "Alan Turing",
        "Benedict Cumberbatch",
        2,
        "movie",
        71,
        emptyList(),
        null
    ),
    Citation(
        87,
        "You just need to believe in yourself!",
        "Il faut juste que tu crois en toi !",
        null,
        null,
        "",
        "",
        2,
        "movie",
        72,
        emptyList(),
        null
    ),
    Citation(
        88,
        "Hasta la vista, baby.",
        "Hasta la vista, baby.",
        null,
        null,
        "The Terminator",
        "Arnold Schwarzenegger",
        2,
        "movie",
        73,
        emptyList(),
        null
    ),
    Citation(
        89,
        "I'll be back.",
        "Je reviendrai.",
        null,
        null,
        "The Terminator",
        "Arnold Schwarzenegger",
        2,
        "movie",
        74,
        emptyList(),
        null
    ),
    Citation(
        90,
        "Here’s Johnny!",
        "C'est moi, Johnny !",
        null,
        null,
        "Jack Torrance",
        "Jack Nicholson",
        2,
        "movie",
        75,
        emptyList(),
        null
    ),
    Citation(
        91,
        "Run, Forrest, run!",
        "Cours Forrest, cours !",
        null,
        null,
        "Jenny",
        "",
        2,
        "movie",
        5,
        emptyList(),
        null
    ),
    Citation(
        92,
        "Mama always said life was like a box of chocolates. You never know what you’re gonna get.",
        "Maman disait toujours, la vie c'est comme une boîte de chocolats, on ne sait jamais sur quoi on va tomber.",
        null,
        null,
        "Forrest Gump",
        "",
        1,
        "movie",
        5,
        emptyList(),
        null
    ),
    Citation(
        93,
        "Are you not entertained?",
        "Ça vous divertit, hein ?",
        null,
        null,
        "Maximus",
        "",
        2,
        "movie",
        0,
        emptyList(),
        null
    ),
    Citation(
        94,
        "I’ll make him an offer he can’t refuse.",
        "Je vais lui faire une offre qu'il ne pourra pas refuser.",
        null,
        null,
        "Don Corleone",
        "Marlon Brando",
        1,
        "movie",
        1,
        emptyList(),
        null
    ),
    Citation(
        95,
        "Say hello to my little friend!",
        "Dis bonjour à mon petit ami !",
        null,
        null,
        "Tony Montana",
        "Al Pacino",
        2,
        "movie",
        3,
        emptyList(),
        null
    ),
    Citation(
        96,
        "May the Force be with you.",
        "Que la force soit avec toi.",
        null,
        null,
        "",
        "",
        2,
        "movie",
        76,
        emptyList(),
        null
    ),
    Citation(
        97,
        "La vie est un long fleuve tranquille, surtout pour ceux qui sont sur le bateau.",
        "La vie est un long fleuve tranquille, surtout pour ceux qui sont sur le bateau.",
        null,
        null,
        "Vinz",
        "Vincent Cassel",
        2,
        "movie",
        77,
        emptyList(),
        null
    ),
    Citation(
        98,
        "You can't change the past, but you can influence the future.",
        "On ne peut pas changer le passé, mais on peut influencer l'avenir.",
        null,
        null,
        "Marty McFly",
        "Michael J. Fox",
        1,
        "movie",
        78,
        emptyList(),
        null
    ),
    Citation(
        99,
        "Happiness is not a destination, it's a journey.",
        "Le bonheur n'est pas une destination, c'est un voyage.",
        null,
        null,
        "Chris Gardner",
        "Will Smith",
        2,
        "movie",
        79,
        emptyList(),
        null
    ),
    Citation(
        100,
        "Truths aren't truths, they're what we make of them.",
        "Les vérités ne sont pas des vérités, elles sont ce que l'on en fait.",
        null,
        null,
        "Mal",
        "Marion Cotillard",
        2,
        "movie",
        80,
        emptyList(),
        null
    ),
    Citation(
        101,
        "There are monsters in this world that aren't made of flesh and blood.",
        "Il y a des monstres dans ce monde qui ne sont pas de chair et de sang.",
        null,
        null,
        "Eleven",
        "Millie Bobby Brown",
        2,
        "serie",
        81,
        emptyList(),
        null
    ),
    Citation(
        102,
        "Good and evil are not absolute concepts.",
        "Le bien et le mal ne sont pas des concepts absolus.",
        null,
        null,
        "Geralt",
        "Henry Cavill",
        2,
        "serie",
        82,
        emptyList(),
        null
    ),
    Citation(
        103,
        "There are no shortcuts to places worth going.",
        "Il n'y a pas de raccourcis pour les endroits qui valent la peine d'aller.",
        null,
        null,
        "Aragorn",
        "Viggo Mortensen",
        2,
        "movie",
        83,
        emptyList(),
        null
    ),
    Citation(
        104,
        "The best secrets are the ones we share.",
        "Les meilleurs secrets sont ceux qu'on partage.",
        null,
        null,
        "Sherlock Holmes",
        "Robert Downey Jr.",
        1,
        "movie",
        84,
        emptyList(),
        null
    ),
    Citation(
        105,
        "Aim for the moon, because even if you miss, you'll land among the stars.",
        "Il faut toujours viser la lune, car même en cas d'échec, on atterrit dans les étoiles.",
        null,
        null,
        "Jim Lovell",
        "Tom Hanks",
        3,
        "movie",
        85,
        emptyList(),
        null
    ),
    Citation(
        106,
        "The only thing that separates us from the animals is our conscience.",
        "La seule chose qui nous sépare des animaux, c'est la conscience.",
        null,
        null,
        "Dr. Ian Malcolm",
        "Jeff Goldblum",
        1,
        "movie",
        10,
        emptyList(),
        null
    ),
    Citation(
        107,
        "There are no shortcuts to the top.",
        "Il n'y a pas de raccourcis pour arriver au sommet.",
        null,
        null,
        "Bruce Wayne",
        "Christian Bale",
        2,
        "movie",
        86,
        emptyList(),
        null
    ),
    Citation(
        108,
        "Heroes aren't born, they are made.",
        "Les héros ne naissent pas, ils se font.",
        null,
        null,
        "Bruce Wayne",
        "Christian Bale",
        1,
        "movie",
        87,
        emptyList(),
        null
    ),
    Citation(
        109,
        "It's okay to change your mind, that's how you grow.",
        "Il n'y a pas de mal à changer d'avis, c'est ce qui fait grandir.",
        null,
        null,
        "Andy Dufresne",
        "Tim Robbins",
        2,
        "movie",
        88,
        emptyList(),
        null
    ),
    Citation(
        110,
        "Humanity is like a spark in the dark.",
        "L'humanité est comme une étincelle dans le noir.",
        null,
        null,
        "Cooper",
        "Matthew McConaughey",
        1,
        "movie",
        21,
        emptyList(),
        null
    ),
    Citation(
        111,
        "Memories are the treasures we keep forever.",
        "Les souvenirs sont les trésors que nous gardons pour toujours.",
        null,
        null,
        "Joel Barish",
        "Jim Carrey",
        2,
        "movie",
        89,
        emptyList(),
        null
    ),
    Citation(
        112,
        "We are not heroes, but we can do heroic things.",
        "Nous ne sommes pas des héros, mais nous pouvons faire des choses héroïques.",
        null,
        null,
        "Tony Stark",
        "Robert Downey Jr.",
        1,
        "movie",
        27,
        emptyList(),
        null
    ),
    Citation(
        113,
        "Courage is not the absence of fear, but the ability to overcome it.",
        "Le courage n'est pas l'absence de peur, mais la capacité de la vaincre.",
        null,
        null,
        "William Wallace",
        "Mel Gibson",
        1,
        "movie",
        90,
        emptyList(),
        null
    ),
    Citation(
        114,
        "Nothing is impossible for those who dare to dream.",
        "Rien n'est impossible pour ceux qui osent rêver.",
        null,
        null,
        "Mufasa",
        "James Earl Jones",
        2,
        "movie",
        91,
        emptyList(),
        null
    ),
    Citation(
        115,
        "Reality is often disappointing.",
        "La réalité est souvent décevante.",
        null,
        null,
        "Neo",
        "Keanu Reeves",
        2,
        "movie",
        92,
        emptyList(),
        null
    ),
    Citation(
        116,
        "The greatest danger is not taking any risks at all.",
        "Le plus grand danger est de ne pas en prendre du tout.",
        null,
        null,
        "Dom Cobb",
        "Leonardo DiCaprio",
        2,
        "movie",
        80,
        emptyList(),
        null
    ),
    Citation(
        117,
        "You never lose as long as you don't give up.",
        "On ne perd jamais tant qu'on ne lâche pas.",
        null,
        null,
        "Rocky Balboa",
        "Sylvester Stallone",
        1,
        "movie",
        55,
        emptyList(),
        null
    ),
    Citation(
        118,
        "The beauty of life lies in the little things.",
        "La beauté de la vie réside dans les petites choses.",
        null,
        null,
        "Amélie Poulain",
        "Audrey Tautou",
        2,
        "movie",
        93,
        emptyList(),
        null
    )
)