package com.example.citationeapp.di

import com.example.citationeapp.data.models.Citation

val citations = mutableListOf(
    Citation(
        0,
        "Are You Not Entertained ?",
        "Est-ce que vous n'êtes pas divertis ?",
        "Gladiator",
        "Gladiator",
        null,
        null,
        "Maximus",
        "Russell Crowe",
        2,
        "movie",
        null
    ),
    Citation(
        1,
        "Death smiles at us all, all we can do is smile back.",
        "La mort nous sourit tous, tout ce que nous pouvons faire, c'est lui sourire en retour.",
        "Gladiator",
        "Gladiator",
        null,
        null,
        "Maximus",
        "Russell Crowe",
        1,
        "movie",
        null
    ),
    Citation(
        2,
        "I will make him an offer he can't refuse.",
        "Je vais lui faire une offre qu'il ne pourra pas refuser.",
        "The Godfather",
        "Le Parrain",
        null,
        null,
        "Vito Corleone",
        "Marlon Brando",
        1,
        "movie",
        null
    ),
    Citation(
        3,
        "Me? I'm dishonest, and a dishonest man you can always trust to be dishonest. Honestly. It's the honest ones you want to watch out for, because you can never predict when they're going to do something incredibly... stupid.",
        "Moi ? Je suis malhonnête, et on sait qu'un homme malhonnête le restera quoiqu'il arrive. Honnêtement. Ce sont les hommes honnêtes dont il faut se méfier, car on peut jamais prévoir à quel moment ils font quelque chose d'incroyablement... stupide.",
        "Pirates of the Caribbean: The Curse of the Black Pearl",
        "Pirates des Caraïbes : La Malédiction du Black Pearl",
        null,
        null,
        "Jack Sparrow",
        "Johnny Depp",
        3,
        "movie",
        null
    ),
    Citation(
        4,
        "Say hello to my little friend!",
        "Dis bonjour à mon petit ami !",
        "Scarface",
        "Scarface",
        null,
        null,
        "Tony Montana",
        "Al Pacino",
        2,
        "movie",
        null
    ),
    Citation(
        5,
        "Hasta la vista, baby.",
        "Hasta la vista, baby.",
        "Terminator 2: Judgment Day",
        "Terminator 2 : Le Jugement dernier",
        null,
        null,
        "T-800",
        "Arnold Schwarzenegger",
        1,
        "movie",
        null
    ),
    Citation(
        6,
        "Life is like a box of chocolates. You never know what you're gonna get.",
        "La vie, c'est comme une boîte de chocolats. On ne sait jamais sur quoi on va tomber.",
        "Forrest Gump",
        "Forrest Gump",
        null,
        null,
        "Forrest Gump",
        "Tom Hanks",
        1,
        "movie",
        null
    ),
    Citation(
        7,
        "I am your father.",
        "Je suis ton père.",
        "Star Wars: The Empire Strikes Back",
        "Star Wars : L'Empire contre-attaque",
        null,
        null,
        "Darth Vader",
        "James Earl Jones",
        1,
        "movie",
        null
    ),
    Citation(
        8,
        "Do or do not, there is no try.",
        "Fais-le ou ne le fais pas, mais il n'y a pas d'essai.",
        "Star Wars: The Empire Strikes Back",
        "Star Wars : L'Empire contre-attaque",
        null,
        null,
        "Yoda",
        "Frank Oz",
        2,
        "movie",
        null
    ),
    Citation(
        9,
        "I see dead people.",
        "Je vois des gens qui sont morts.",
        "The Sixth Sense",
        "Sixième Sens",
        null,
        null,
        "Cole Sear",
        "Haley Joel Osment",
        2,
        "movie",
        null
    ),
    Citation(
        10,
        "That Belongs in a Museum.",
        "Ça appartient à un musée.",
        "Indiana Jones and the Last Crusade",
        "Indiana Jones et la Dernière Croisade",
        null,
        null,
        "Indiana Jones",
        "Harrison Ford",
        2,
        "movie",
        null
    ),
    Citation(
        11,
        "Keep your friends close, but your enemies closer.",
        "Garde tes amis près de toi, mais encore plus près tes ennemis.",
        "The Godfather Part II",
        "Le Parrain, 2e partie",
        null,
        null,
        "Michael Corleone",
        "Al Pacino",
        3,
        "movie",
        null
    ),
    Citation(
        12,
        "I spared no expense!",
        "Je n'ai pas regardé à la dépense !",
        "Jurassic Park",
        "Jurassic Park",
        null,
        null,
        "John Hammond",
        "Richard Attenborough",
        2,
        "movie",
        null
    ),
    Citation(
        13,
        "Certainty of death. Small chance of success. What are we waiting for?",
        "Certitude de mort. Petite chance de succès. Qu'attendons-nous ?",
        "The Lord of the Rings: The Return of the King",
        "Le Seigneur des anneaux : Le Retour du roi",
        null,
        null,
        "Gimli",
        "John Rhys-Davies",
        2,
        "movie",
        null
    ),
    Citation(
        14,
        "Fly, you fools!",
        "Fuyez, pauvres fous !",
        "The Lord of the Rings: The Fellowship of the Ring",
        "Le Seigneur des anneaux : La Communauté de l'anneau",
        null,
        null,
        "Gandalf",
        "Ian McKellen",
        2,
        "movie",
        null
    ),
    Citation(
        15,
        "I can't carry it for you, but I can carry you!",
        "Je ne peux pas le porter pour toi, mais je peux te porter, toi !",
        "The Lord of the Rings: The Return of the King",
        "Le Seigneur des anneaux : Le Retour du roi",
        null,
        null,
        "Samwise Gamgee",
        "Sean Astin",
        1,
        "movie",
        null
    ),
    Citation(
        16,
        "If we are to be successful, we must show tact, respect, and a good deal of charm. That's why you must let me do the talking!",
        "Si nous voulons réussir, nous devons faire preuve de tact, de respect et d'un certain charme. C'est pourquoi tu dois me laisser parler !",
        "The Hobbit: An Unexpected Journey",
        "Le Hobbit : Un voyage inattendu",
        null,
        null,
        "Gandalf",
        "Ian McKellen",
        2,
        "movie",
        null
    ),
    Citation(
        17,
        "Est-ce que j'me suis bien fait compris ?",
        "Est-ce que j'me suis bien fait compris ?",
        "Taxi 4",
        "Taxi 4",
        null,
        null,
        "Commissaire Gibert",
        "Bernard Farcy",
        1,
        "movie",
        null
    ),
    Citation(
        18,
        "Voilà, cadeau ... de Noël !",
        "Voilà, cadeau ... de Noël !",
        "OSS 117 : Rio ne répond plus",
        "OSS 117 : Rio ne répond plus",
        null,
        null,
        "OSS 117",
        "Jean Dujardin",
        2,
        "movie",
        null
    ),
    Citation(
        19,
        "Il y a forcément une amicale d'anciens nazis ? Ou un club ? Une association ?",
        "Il y a forcément une amicale d'anciens nazis ? Ou un club ? Une association ?",
        "OSS 117: Lost in Rio",
        "OSS 117 : Rio ne répond plus",
        null,
        null,
        "OSS 117",
        "Jean Dujardin",
        1,
        "movie",
        null
    ),
    Citation(
        20,
        "J'aime me beurrer la biscotte !",
        "J'aime me beurrer la biscotte !",
        "OSS 117 : Le Caire, nid d'espions",
        "OSS 117 : Le Caire, nid d'espions",
        null,
        null,
        "OSS 117",
        "Jean Dujardin",
        1,
        "movie",
        null
    ),
    Citation(
        21,
        "Tu n'es pas seulement un lâche, tu es un traître comme ta petite taille le laisser deviner.",
        "Tu n'es pas seulement un lâche, tu es un traître comme ta petite taille le laisser deviner.",
        "OSS 117 : Le Caire, nid d'espions",
        "OSS 117 : Le Caire, nid d'espions",
        null,
        null,
        "OSS 117",
        "Jean Dujardin",
        2,
        "movie",
        null
    ),
    Citation(
        22,
        "C'est quoi ce pays ? C'est pas possible. Il fait au moins moins 8000 !",
        "C'est quoi ce pays ? C'est pas possible. Il fait au moins moins 8000 !",
        "Astérix & Obélix : Mission Cléopâtre",
        "Astérix & Obélix : Mission Cléopâtre",
        null,
        null,
        "Numérobis",
        "Jamel Debbouze",
        1,
        "movie",
        null
    ),
    Citation(
        23,
        "Je vais rester ici pour raviver le feu, parce que parfois il s'éteint.",
        "Je vais rester ici pour raviver le feu, parce que parfois il s'éteint.",
        "Astérix & Obélix : Mission Cléopâtre",
        "Astérix & Obélix : Mission Cléopâtre",
        null,
        null,
        "Numérobis",
        "Jamel Debbouze",
        2,
        "movie",
        null
    ),
    Citation(
        24,
        "It takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends.",
        "Il faut beaucoup de courage pour affronter nos ennemis, mais il en faut tout autant pour affronter ses amis.",
        "Harry Potter and the Philosopher's Stone",
        "Harry Potter à l'école des sorciers",
        null,
        null,
        "Albus Dumbledore",
        "Richard Harris",
        2,
        "movie",
        null
    ),
    Citation(
        25,
        "I solemnly swear that I am up to no good.",
        "Je jure solennellement que mes intentions sont mauvaises.",
        "Harry Potter and the Prisoner of Azkaban",
        "Harry Potter et le Prisonnier d'Azkaban",
        null,
        null,
        "Fred & George Weasley",
        "James & Oliver Phelps",
        1,
        "movie",
        null
    ),
    Citation(
        26,
        "The thing that frightens you most is fear itself, which is a wise thing.",
        "La chose qui t'effraie le plus, c'est la peur elle-même, ce qui est une chose sage.",
        "Harry Potter and the Prisoner of Azkaban",
        "Harry Potter et le Prisonnier d'Azkaban",
        null,
        null,
        "Remus Lupin",
        "David Thewlis",
        2,
        "movie",
        null
    ),
    Citation(
        27,
        "When we dream, we enter a world that is entirely our own.",
        "Quand nous rêvons, nous entrons dans un monde qui est entièrement le nôtre.",
        "Harry Potter and the Prisoner of Azkaban",
        "Harry Potter et le Prisonnier d'Azkaban",
        null,
        null,
        "Albus Dumbledore",
        "Michael Gambon",
        2,
        "movie",
        null
    ),
    Citation(
        28,
        "Soon, we must all face the choice between what is right and what is easy.",
        "Bientôt, nous devrons tous affronter le choix entre ce qui est juste et ce qui est facile.",
        "Harry Potter and the Goblet of Fire",
        "Harry Potter et la Coupe de feu",
        null,
        null,
        "Albus Dumbledore",
        "Michael Gambon",
        2,
        "movie",
        null
    ),
    Citation(
        29,
        "Mankind was born on Earth. It was never meant to die here.",
        "L'humanité est née sur Terre. Elle n'était pas censée y mourir.",
        "Interstellar",
        "Interstellar",
        null,
        null,
        "Cooper",
        "Matthew McConaughey",
        2,
        "movie",
        null
    ),
    Citation(
        30,
        "Get busy living, or get busy dying.",
        "Occupe-toi de vivre ou occupe-toi de mourir.",
        "The Shawshank Redemption",
        "Les Évadés",
        null,
        null,
        "Andy Dufresne",
        "Tim Robbins",
        2,
        "movie",
        null
    ),
    Citation(
        31,
        "Any man who must say \"I am the king\" is no true king.",
        "Tout homme qui doit dire \"je suis le roi\" n'est pas un vrai roi.",
        "Game of Thrones",
        "Game of Thrones",
        null,
        null,
        "Tywin Lannister",
        "Charles Dance",
        2,
        "serie",
        null
    ),
    Citation(
        32,
        "A mind needs books as a sword needs a whetstone if it is to keep its edge. That's why I read so much.",
        "Un esprit a besoin de livres comme une épée a besoin d'une pierre à aiguiser pour conserver son tranchant. C'est pour ça que je lis autant.",
        "Game of Thrones",
        "Game of Thrones",
        null,
        null,
        "Tyrion Lannister",
        "Peter Dinklage",
        2,
        "serie",
        null
    ),
    Citation(
        33,
        "Lies spread faster than the truth.",
        "Les mensonges se propagent plus vite que la vérité.",
        "Peaky Blinders",
        "Peaky Blinders",
        null,
        null,
        "Tommy Shelby",
        "Cillian Murphy",
        2,
        "movie",
        null
    ),
    Citation(
        34,
        "This is the way.",
        "C'est la voie.",
        "The Mandalorian",
        "The Mandalorian",
        null,
        null,
        "The Mandalorian",
        "Pedro Pascal",
        1,
        "serie",
        null
    ),
    Citation(
        35,
        "Monseigneur, c'est de l'or ! De l'or pour vous réveiller !",
        "Monseigneur, c'est de l'or ! De l'or pour vous réveiller !",
        "La Folie des grandeurs",
        "La Folie des grandeurs",
        null,
        null,
        "Blaze",
        "Yves Montand",
        2,
        "movie",
        null
    ),
    Citation(
        36,
        "I love you three thousand times more.",
        "Je t'aime trois mille fois plus.",
        "Avengers: Endgame",
        "Avengers : Endgame",
        null,
        null,
        "Morgan Stark",
        "Lexi Rabe",
        2,
        "movie",
        null
    ),
    Citation(
        37,
        "Tu es comme le H de Hawaï, tu sers à rien.",
        "Tu es comme le H de Hawaï, tu sers à rien.",
        "Brice de Nice",
        "Brice de Nice",
        null,
        null,
        "Brice",
        "Jean Dujardin",
        2,
        "movie",
        null
    ),
    Citation(
        38,
        "Sometimes your whole life boils down to one insane move.",
        "Parfois, toute votre vie se résume à un geste insensé.",
        "Avatar",
        "Avatar",
        null,
        null,
        "Jake Sully",
        "Sam Worthington",
        2,
        "movie",
        null
    ),
    Citation(
        39,
        "Champions du monde !",
        "Champions du monde !",
        "La vérité si je mens",
        "La vérité si je mens",
        null,
        null,
        "Serge Benamou",
        "José Garcia",
        2,
        "movie",
        null
    ),
    Citation(
        40,
        "Daddy, I want another pony!",
        "Papa, je veux un autre poney !",
        "Charlie and the Chocolate Factory",
        "Charlie et la Chocolaterie",
        null,
        null,
        "Veruca Salt",
        "Julia Winter",
        2,
        "movie",
        null
    ),
    Citation(
        41,
        "Pas commencer à jouer avec mes couilles, ok ?",
        "Pas commencer à jouer avec mes couilles, ok ?",
        "Dikkenek",
        "Dikkenek",
        null,
        null,
        "Claudy Focan",
        "François Damiens",
        1,
        "movie",
        null
    ),
    Citation(
        42,
        "Il a une tête de vainqueur.",
        "Il a une tête de vainqueur.",
        "Le Dîner de Cons",
        "Le Dîner de Cons",
        null,
        null,
        "Pierre Brochant",
        "Thierry Lhermitte",
        1,
        "movie",
        null
    ),
    Citation(
        43,
        "Ohhh, c'est très tordu, mais terriblement astucieux.",
        "Ohhh, c'est très tordu, mais terriblement astucieux.",
        "Le Dîner de Cons",
        "Le Dîner de Cons",
        null,
        null,
        "François Pignon",
        "Jacques Villeret",
        1,
        "movie",
        null
    ),
    Citation(
        44,
        "You see, in this world, there are two kinds of people, my friend: Those with loaded guns, and those who dig. You dig.",
        "Tu vois, dans ce monde, il y a deux catégories de personnes, mon ami : ceux qui ont un pistolet chargé et ceux qui creusent. Toi, tu creuses.",
        "The Good, the Bad and the Ugly",
        "Le Bon, la Brute et le Truand",
        null,
        null,
        "Blondie",
        "Clint Eastwood",
        2,
        "movie",
        null
    ),
    Citation(
        45,
        "Si j'avais su, je ne serais pas venu.",
        "Si j'avais su, je ne serais pas venu.",
        "La Guerre des boutons",
        "La Guerre des boutons",
        null,
        null,
        "Petit Gibus",
        "Martin Lartigue",
        1,
        "movie",
        null
    ),
    Citation(
        46,
        "You talkin' to me? You talkin' to ME? You talkin' to me?",
        "C'est à moi que tu parles ? C'est à moi que tu parles ? C'est à moi que tu parles ?",
        "Taxi Driver",
        "Taxi Driver",
        null,
        null,
        "Travis Bickle",
        "Robert De Niro",
        1,
        "movie",
        null
    ),
    Citation(
        47,
        "I will not part with a single piece of gold, not the smallest bit.",
        "Je ne me séparerai d'aucun morceau d'or, pas le plus petit.",
        "The Hobbit: The Battle of the Five Armies",
        "Le Hobbit : La Bataille des Cinq Armées",
        null,
        null,
        "Thorin Oakenshield",
        "Richard Armitage",
        2,
        "movie",
        null
    ),
    Citation(
        48,
        "Au revoir, Shoshanna!",
        "Au revoir, Shoshanna !",
        "Inglourious Basterds",
        "Inglourious Basterds",
        null,
        null,
        "Col. Hans Landa",
        "Christoph Waltz",
        1,
        "movie",
        null
    ),
    Citation(
        49,
        "I used to think my life was a tragedy, but now I realize it's a comedy.",
        "Je pensais que ma vie était une tragédie, mais maintenant je me rends compte que c'est une comédie.",
        "Joker",
        "Joker",
        null,
        null,
        "Arthur Fleck",
        "Joaquin Phoenix",
        2,
        "movie",
        null
    ),
    Citation(
        50,
        "Yesterday is history, tomorrow is a mystery, but today is a gift. That is why it is called the present.",
        "Hier est derrière, demain est mystère, et aujourd'hui est un cadeau, c'est pour cela qu'on l'appelle le présent.",
        "Kung Fu Panda",
        "Kung Fu Panda",
        null,
        null,
        "Master Oogway",
        "",
        2,
        "movie",
        null
    ),
    Citation(
        51,
        "J'ai glissé chef !",
        "J'ai glissé chef !",
        "Mais où est donc passée la septième compagnie ?",
        "Mais où est donc passée la septième compagnie ?",
        null,
        null,
        "Pitivier",
        "",
        2,
        "movie",
        null
    ),
    Citation(
        52,
        "I expected nothing, and I’m still let down.",
        "Je m'attendais à rien et je suis quand même déçu.",
        "Malcolm",
        "Malcolm",
        null,
        null,
        "Dewey",
        "",
        2,
        "serie",
        null
    ),
    Citation(
        53,
        "You live. You live. You die.",
        "Toi, tu vis. Toi, tu vis. Toi, tu crèves.",
        "Malcolm",
        "Malcolm",
        null,
        null,
        "Dewey",
        "",
        1,
        "serie",
        null
    ),
    Citation(
        54,
        "The difference between you and me is that I make this look good.",
        "La différence entre toi et moi, c'est que moi j'ai la classe.",
        "Men in Black",
        "Men in Black",
        null,
        null,
        "J",
        "Will Smith",
        2,
        "movie",
        null
    ),
    Citation(
        55,
        "Les filles c'est comme les penaltys : si tu gamberches trop t'as aucune chance de planter.",
        "Les filles c'est comme les penaltys : si tu gamberches trop t'as aucune chance de planter.",
        "Neuilly sa mère",
        "Neuilly sa mère",
        null,
        null,
        "",
        "",
        2,
        "movie",
        null
    ),
    Citation(
        56,
        "Lies are necessary when the truth is too difficult to believe.",
        "Les mensonges sont nécessaires quand la vérité est trop difficile à croire.",
        "Narcos",
        "Narcos",
        null,
        null,
        "Pablo Escobar",
        "",
        2,
        "serie",
        null
    ),
    Citation(
        57,
        "History isn’t kind to men who play God.",
        "L'histoire n'est pas très indulgente avec les hommes qui se prennent pour Dieu.",
        "No Time to Die",
        "Mourir peut attendre",
        null,
        null,
        "James Bond",
        "Daniel Craig",
        1,
        "movie",
        null
    ),
    Citation(
        58,
        "I totally agree with the fat one.",
        "J'suis bien d'accord avec la grosse là.",
        "Nos jours heureux",
        "Nos jours heureux",
        null,
        null,
        "",
        "",
        1,
        "movie",
        null
    ),
    Citation(
        59,
        "Tu es le roi des cons au pays des emmerdeurs.",
        "Tu es le roi des cons au pays des emmerdeurs.",
        "Nos jours heureux",
        "Nos jours heureux",
        null,
        null,
        "Caroline",
        "",
        1,
        "movie",
        null
    ),
    Citation(
        60,
        "They won’t fear it until they understand it. And they won’t understand it until they’ve used it.",
        "Ils ne la craindront pas tant qu'ils ne l'auront pas comprise. Et ils ne la comprendront pas tant qu'ils ne l'auront pas utilisée.",
        "Oppenheimer",
        "Oppenheimer",
        null,
        null,
        "Robert Oppenheimer",
        "Cillian Murphy",
        2,
        "movie",
        null
    ),
    Citation(
        61,
        "Now I am become Death, the destroyer of worlds.",
        "Maintenant, je suis devenu la Mort, le destructeur des mondes.",
        "Oppenheimer",
        "Oppenheimer",
        null,
        null,
        "Robert Oppenheimer",
        "Cillian Murphy",
        1,
        "movie",
        null
    ),
    Citation(
        62,
        "Vous pouvez pas me taper, j'ai des lunettes.",
        "Vous pouvez pas me taper, j'ai des lunettes.",
        "Le Petit Nicolas",
        "Le Petit Nicolas",
        null,
        null,
        "Agnan",
        "",
        2,
        "movie",
        null
    ),
    Citation(
        63,
        "Mais enfin j'suis le parrain de ton fils !",
        "Mais enfin j'suis le parrain de ton fils !",
        "Les Petits Mouchoirs",
        "Les Petits Mouchoirs",
        null,
        null,
        "",
        "François Cluzet",
        1,
        "movie",
        null
    ),
    Citation(
        64,
        "Death is a day worth living for.",
        "La mort est une journée qui mérite d'être vécue.",
        "Pirates of the Caribbean: At World's End",
        "Pirates des Caraïbes, jusqu'au bout du monde",
        null,
        null,
        "Hector Barbossa",
        "Geoffrey Rush",
        2,
        "movie",
        null
    ),
    Citation(
        65,
        "Anyone can cook.",
        "Tout le monde peut cuisiner.",
        "Ratatouille",
        "Ratatouille",
        null,
        null,
        "",
        "",
        1,
        "movie",
        null
    ),
    Citation(
        66,
        "Roads? Where we're going, we don't need roads.",
        "La route ? Là où on va, on n'a pas besoin de route !",
        "Back to the Future",
        "Retour vers le futur",
        null,
        null,
        "Doc",
        "",
        2,
        "movie",
        null
    ),
    Citation(
        67,
        "Great Scott!",
        "Non de Zeus !",
        "Back to the Future",
        "Retour vers le futur",
        null,
        null,
        "Doc",
        "",
        1,
        "movie",
        null
    ),
    Citation(
        68,
        "Je sais pas comment on fait une tête d'innocent, depuis tout petit j'suis coupable.",
        "Je sais pas comment on fait une tête d'innocent, depuis tout petit j'suis coupable.",
        "Rien à déclarer",
        "Rien à déclarer",
        null,
        null,
        "",
        "",
        1,
        "movie",
        null
    ),
    Citation(
        69,
        "It ain't about how hard you can hit, it’s about how hard you can get hit and keep moving forward.",
        "Ce qui compte c'est pas le nombre de coups que tu peux donner, mais c'est le nombre que tu peux encaisser et continuer à avancer.",
        "Rocky",
        "Rocky",
        null,
        null,
        "Rocky Balboa",
        "",
        1,
        "movie",
        null
    ),
    Citation(
        70,
        "I am one with the Force, and the Force is with me.",
        "Je fais corps avec la Force, la Force est avec moi.",
        "Rogue One: A Star Wars Story",
        "Rogue One: A Star Wars Story",
        null,
        null,
        "Chirrut Îmwe",
        "",
        1,
        "movie",
        null
    ),
    Citation(
        71,
        "Is it better to live as a monster or die as a good man?",
        "Mieux vaut-il vivre comme un monstre ou mourir en homme bien ?",
        "Shutter Island",
        "Shutter Island",
        null,
        null,
        "Teddy Daniels",
        "Leonardo DiCaprio",
        1,
        "movie",
        null
    ),
    Citation(
        72,
        "With great power comes great responsibility.",
        "à grand pouvoir, grandes responsabilités.",
        "Spider-Man",
        "Spider-Man",
        null,
        null,
        "Spider-Man",
        "",
        1,
        "movie",
        null
    ),
    Citation(
        73,
        "Just because you have the ability to speak does not make you intelligent.",
        "Ce n'est pas parce que tu parles que tu es intelligent.",
        "Star Wars: Episode I - The Phantom Menace",
        "Star Wars: Episode I - La Menace Fantôme",
        null,
        null,
        "Qui-Gon Jinn",
        "Liam Neeson",
        2,
        "movie",
        null
    ),
    Citation(
        74,
        "I don’t like sand. It’s coarse and rough and irritating and it gets everywhere.",
        "Je n'aime pas le sable, il est grossier, agressif, irritant et s'insinue partout.",
        "Star Wars: Episode II - Attack of the Clones",
        "Star Wars: Episode II - L'Attaque des Clones",
        null,
        null,
        "Anakin Skywalker",
        "Hayden Christensen",
        1,
        "movie",
        null
    ),
    Citation(
        75,
        "L'animal qu'on croyait qu'il n'existait pas mais en fait qu'il n'existe !",
        "L'animal qu'on croyait qu'il n'existait pas mais en fait qu'il n'existe !",
        "On the Trail of the Marsupilami",
        "Sur la piste du Marsupilami",
        null,
        null,
        "Pablito",
        "Jamel Debbouze",
        1,
        "movie",
        null
    ),
    Citation(
        76,
        "Red alert!",
        "Alerte générale !",
        "Taxi",
        "Taxi",
        null,
        null,
        "Commissaire Gibert",
        "",
        1,
        "movie",
        null
    ),
    Citation(
        77,
        "He saved me in every way a person can be saved.",
        "Il m'a sauvée de toutes les façons possibles dont on peut sauver une personne.",
        "Titanic",
        "Titanic",
        null,
        null,
        "Rose",
        "",
        2,
        "movie",
        null
    ),
    Citation(
        78,
        "Arrêtez ! Ou je tire une balle dans la tête à la main !",
        "Arrêtez ! Ou je tire une balle dans la tête à la main !",
        "La Tour Montparnasse Infernale",
        "La Tour Montparnasse Infernale",
        null,
        null,
        "Eric",
        "Eric Judor",
        1,
        "movie",
        null
    ),
    Citation(
        79,
        "There’s a snake in my boot!",
        "Il y a un serpent dans ma botte !",
        "Toy Story",
        "Toy Story",
        null,
        null,
        "Woody",
        "",
        2,
        "movie",
        null
    ),
    Citation(
        80,
        "I loved my son from the moment he opened his eyes until the moment you closed them.",
        "J'ai aimé mon garçon du jour ou il a ouvert les yeux jusqu'au moment ou tu les lui as fermés.",
        "Troy",
        "Troie",
        null,
        null,
        "King Priam",
        "",
        2,
        "movie",
        null
    ),
    Citation(
        81,
        "Tu ferais mieux de faire refaire la façade de ta femme plutôt que celle de ta maison !",
        "Tu ferais mieux de faire refaire la façade de ta femme plutôt que celle de ta maison !",
        "Les Tuche",
        "Les Tuche",
        null,
        null,
        "Jeff Tuche",
        "Jean-Paul Rouve",
        1,
        "movie",
        null
    ),
    Citation(
        82,
        "Les gens qui bossent, ils exploitent la planète et puis tant pis si ça pète !",
        "Les gens qui bossent, ils exploitent la planète et puis tant pis si ça pète !",
        "Les Tuche",
        "Les Tuche",
        null,
        null,
        "Jeff Tuche",
        "Jean-Paul Rouve",
        2,
        "movie",
        null
    ),
    Citation(
        83,
        "Tigers love pepper, they hate cinnamon.",
        "Les tigres adorent le poivre, ils détestent la cannelle.",
        "The Hangover",
        "Very Bad Trip",
        null,
        null,
        "Alan",
        "",
        2,
        "movie",
        null
    ),
    Citation(
        84,
        "Messire, messire, un sarrasin dans une charriote du diable ! c'est tout ferré y'a point de beuf pour tirer !",
        "Messire, messire, un sarrasin dans une charriote du diable ! c'est tout ferré y'a point de beuf pour tirer !",
        "The Visitors",
        "Les Visiteurs",
        null,
        null,
        "Jacquouille",
        "Christian Clavier",
        1,
        "movie",
        null
    ),
    Citation(
        85,
        "Time is of no importance, only life is important.",
        "Le temps est sans importance, seule la vie est importante.",
        "The Fifth Element",
        "Le Cinquième Élément",
        null,
        null,
        "",
        "",
        2,
        "movie",
        null
    ),
    Citation(
        86,
        "Sometimes it is the people no one imagines anything of who do the things that no one can imagine.",
        "Parfois ce sont les gens que personne n'aurait imaginé qui accomplissent des choses que personne n'avait imaginé.",
        "The Imitation Game",
        "The Imitation Game",
        null,
        null,
        "Alan Turing",
        "Benedict Cumberbatch",
        2,
        "movie",
        null
    ),
    Citation(
        87,
        "You just need to believe in yourself!",
        "Il faut juste que tu crois en toi !",
        "The Incredibles",
        "Les Indestructibles",
        null,
        null,
        "",
        "",
        2,
        "movie",
        null
    ),
    Citation(
        88,
        "Hasta la vista, baby.",
        "Hasta la vista, baby.",
        "Terminator 2: Judgment Day",
        "Terminator 2 : Le Jugement Dernier",
        null,
        null,
        "The Terminator",
        "Arnold Schwarzenegger",
        2,
        "movie",
        null
    ),
    Citation(
        89,
        "I'll be back.",
        "Je reviendrai.",
        "The Terminator",
        "Terminator",
        null,
        null,
        "The Terminator",
        "Arnold Schwarzenegger",
        2,
        "movie",
        null
    ),
    Citation(
        90,
        "Here’s Johnny!",
        "C'est moi, Johnny !",
        "The Shining",
        "Shining",
        null,
        null,
        "Jack Torrance",
        "Jack Nicholson",
        2,
        "movie",
        null
    ),
    Citation(
        91,
        "Run, Forrest, run!",
        "Cours Forrest, cours !",
        "Forrest Gump",
        "Forrest Gump",
        null,
        null,
        "Jenny",
        "",
        2,
        "movie",
        null
    ),
    Citation(
        92,
        "Mama always said life was like a box of chocolates. You never know what you’re gonna get.",
        "Maman disait toujours, la vie c'est comme une boîte de chocolats, on ne sait jamais sur quoi on va tomber.",
        "Forrest Gump",
        "Forrest Gump",
        null,
        null,
        "Forrest Gump",
        "",
        1,
        "movie",
        null
    ),
    Citation(
        93,
        "Are you not entertained?",
        "Ça vous divertit, hein ?",
        "Gladiator",
        "Gladiator",
        null,
        null,
        "Maximus",
        "",
        2,
        "movie",
        null
    ),
    Citation(
        94,
        "I’ll make him an offer he can’t refuse.",
        "Je vais lui faire une offre qu'il ne pourra pas refuser.",
        "The Godfather",
        "Le Parrain",
        null,
        null,
        "Don Corleone",
        "Marlon Brando",
        1,
        "movie",
        null
    ),
    Citation(
        95,
        "Go ahead, make my day.",
        "Vas-y, fais-moi plaisir.",
        "Sudden Impact",
        "Le Retour de l'inspecteur Harry",
        null,
        null,
        "",
        "",
        2,
        "movie",
        null
    ),
    Citation(
        96,
        "Say hello to my little friend!",
        "Dis bonjour à mon petit ami !",
        "Scarface",
        "Scarface",
        null,
        null,
        "Tony Montana",
        "Al Pacino",
        2,
        "movie",
        null
    ),
    Citation(
        97,
        "May the Force be with you.",
        "Que la force soit avec toi.",
        "Star Wars",
        "Star Wars",
        null,
        null,
        "",
        "",
        2,
        "movie",
        null
    ),
    Citation(
        98,
        "La vie est un long fleuve tranquille, surtout pour ceux qui sont sur le bateau.",
        "La vie est un long fleuve tranquille, surtout pour ceux qui sont sur le bateau.",
        "La Haine",
        "La Haine",
        null,
        null,
        "Vinz",
        "Vincent Cassel",
        2,
        "movie",
        null
    ),
    Citation(
        99,
        "You can't change the past, but you can influence the future.",
        "On ne peut pas changer le passé, mais on peut influencer l'avenir.",
        "Back to the Future Part II",
        "Retour vers le futur 2",
        null,
        null,
        "Marty McFly",
        "Michael J. Fox",
        1,
        "movie",
        null
    ),
    Citation(
        100,
        "Happiness is not a destination, it's a journey.",
        "Le bonheur n'est pas une destination, c'est un voyage.",
        "The Pursuit of Happyness",
        "À la recherche du bonheur",
        null,
        null,
        "Chris Gardner",
        "Will Smith",
        2,
        "movie",
        null
    ),
    Citation(
        101,
        "Truths aren't truths, they're what we make of them.",
        "Les vérités ne sont pas des vérités, elles sont ce que l'on en fait.",
        "Inception",
        "Inception",
        null,
        null,
        "Mal",
        "Marion Cotillard",
        2,
        "movie",
        null
    ),
    Citation(
        102,
        "There are monsters in this world that aren't made of flesh and blood.",
        "Il y a des monstres dans ce monde qui ne sont pas de chair et de sang.",
        "Stranger Things",
        "Stranger Things",
        null,
        null,
        "Eleven",
        "Millie Bobby Brown",
        2,
        "serie",
        null
    ),
    Citation(
        103,
        "Good and evil are not absolute concepts.",
        "Le bien et le mal ne sont pas des concepts absolus.",
        "The Witcher",
        "The Witcher",
        null,
        null,
        "Geralt",
        "Henry Cavill",
        2,
        "serie",
        null
    ),
    Citation(
        104,
        "There are no shortcuts to places worth going.",
        "Il n'y a pas de raccourcis pour les endroits qui valent la peine d'aller.",
        "The Lord of the Rings: The Return of the King",
        "Le Seigneur des anneaux : le retour du roi",
        null,
        null,
        "Aragorn",
        "Viggo Mortensen",
        2,
        "movie",
        null
    ),
    Citation(
        105,
        "The best secrets are the ones we share.",
        "Les meilleurs secrets sont ceux qu'on partage.",
        "Sherlock Holmes",
        "Sherlock Holmes",
        null,
        null,
        "Sherlock Holmes",
        "Robert Downey Jr.",
        1,
        "movie",
        null
    ),
    Citation(
        106,
        "Aim for the moon, because even if you miss, you'll land among the stars.",
        "Il faut toujours viser la lune, car même en cas d'échec, on atterrit dans les étoiles.",
        "Apollo 13",
        "Apollo 13",
        null,
        null,
        "Jim Lovell",
        "Tom Hanks",
        3,
        "movie",
        null
    ),
    Citation(
        107,
        "The only thing that separates us from the animals is our conscience.",
        "La seule chose qui nous sépare des animaux, c'est la conscience.",
        "Jurassic Park",
        "Jurassic Park",
        null,
        null,
        "Dr. Ian Malcolm",
        "Jeff Goldblum",
        1,
        "movie",
        null
    ),
    Citation(
        108,
        "There are no shortcuts to the top.",
        "Il n'y a pas de raccourcis pour arriver au sommet.",
        "The Dark Knight Rises",
        "The Dark Knight Rises",
        null,
        null,
        "Bruce Wayne",
        "Christian Bale",
        2,
        "movie",
        null
    ),
    Citation(
        109,
        "Heroes aren't born, they are made.",
        "Les héros ne naissent pas, ils se font.",
        "Batman Begins",
        "Batman Begins",
        null,
        null,
        "Bruce Wayne",
        "Christian Bale",
        1,
        "movie",
        null
    ),
    Citation(
        110,
        "It's okay to change your mind, that's how you grow.",
        "Il n'y a pas de mal à changer d'avis, c'est ce qui fait grandir.",
        "The Shawshank Redemption",
        "Les évadés",
        null,
        null,
        "Andy Dufresne",
        "Tim Robbins",
        2,
        "movie",
        null
    ),
    Citation(
        111,
        "Humanity is like a spark in the dark.",
        "L'humanité est comme une étincelle dans le noir.",
        "Interstellar",
        "Interstellar",
        null,
        null,
        "Cooper",
        "Matthew McConaughey",
        1,
        "movie",
        null
    ),
    Citation(
        112,
        "Memories are the treasures we keep forever.",
        "Les souvenirs sont les trésors que nous gardons pour toujours.",
        "Eternal Sunshine of the Spotless Mind",
        "Eternal Sunshine of the Spotless Mind",
        null,
        null,
        "Joel Barish",
        "Jim Carrey",
        2,
        "movie",
        null
    ),
    Citation(
        113,
        "We are not heroes, but we can do heroic things.",
        "Nous ne sommes pas des héros, mais nous pouvons faire des choses héroïques.",
        "Avengers: Endgame",
        "Avengers : Endgame",
        null,
        null,
        "Tony Stark",
        "Robert Downey Jr.",
        1,
        "movie",
        null
    ),
    Citation(
        114,
        "Courage is not the absence of fear, but the ability to overcome it.",
        "Le courage n'est pas l'absence de peur, mais la capacité de la vaincre.",
        "Braveheart",
        "Braveheart",
        null,
        null,
        "William Wallace",
        "Mel Gibson",
        1,
        "movie",
        null
    ),
    Citation(
        115,
        "Nothing is impossible for those who dare to dream.",
        "Rien n'est impossible pour ceux qui osent rêver.",
        "The Lion King",
        "Le Roi Lion",
        null,
        null,
        "Mufasa",
        "James Earl Jones",
        2,
        "movie",
        null
    ),
    Citation(
        116,
        "Reality is often disappointing.",
        "La réalité est souvent décevante.",
        "The Matrix",
        "Matrix",
        null,
        null,
        "Neo",
        "Keanu Reeves",
        2,
        "movie",
        null
    ),
    Citation(
        117,
        "The greatest danger is not taking any risks at all.",
        "Le plus grand danger est de ne pas en prendre du tout.",
        "Inception",
        "Inception",
        null,
        null,
        "Dom Cobb",
        "Leonardo DiCaprio",
        2,
        "movie",
        null
    ),
    Citation(
        118,
        "You never lose as long as you don't give up.",
        "On ne perd jamais tant qu'on ne lâche pas.",
        "Rocky",
        "Rocky",
        null,
        null,
        "Rocky Balboa",
        "Sylvester Stallone",
        1,
        "movie",
        null
    ),
    Citation(
        119,
        "The beauty of life lies in the little things.",
        "La beauté de la vie réside dans les petites choses.",
        "Amélie",
        "Amélie",
        null,
        null,
        "Amélie Poulain",
        "Audrey Tautou",
        2,
        "movie",
        null
    ),
)